services:
  - type: web  # Changed from worker to web for port binding
    name: whatsapp-bot
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: PORT
        value: 7860  # Must match your app port
      - key: SESSION_ID
        value: Session~
      - key: BOT_INFO
        value: Test
      - key: SUDO
        value: "255772940535"  # Quoted number
      - key: ANTILINK
        value: "true"
